export const NIFTY_50_TICKERS = [
  'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS',
  'HINDUNILVR.NS', 'ITC.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'KOTAKBANK.NS',
  'LT.NS', 'AXISBANK.NS', 'ASIANPAINT.NS', 'MARUTI.NS', 'SUNPHARMA.NS',
  'TITAN.NS', 'BAJFINANCE.NS', 'WIPRO.NS', 'ULTRACEMCO.NS', 'ONGC.NS',
  'NTPC.NS', 'TATASTEEL.NS', 'POWERGRID.NS', 'M&M.NS', 'JSWSTEEL.NS',
  'ADANIENT.NS', 'ADANIPORTS.NS', 'HCLTECH.NS', 'NESTLEIND.NS', 'GRASIM.NS',
  'BAJAJFINSV.NS', 'COALINDIA.NS', 'TECHM.NS', 'INDUSINDBK.NS', 'BPCL.NS',
  'TATACONSUM.NS', 'HEROMOTOCO.NS', 'BRITANNIA.NS', 'DRREDDY.NS', 'CIPLA.NS',
  'EICHERMOT.NS', 'DIVISLAB.NS', 'APOLLOHOSP.NS', 'SBILIFE.NS', 'HDFCLIFE.NS',
  'BAJAJ-AUTO.NS', 'SHRIRAMFIN.NS', 'TRENT.NS', 'BEL.NS', 'INDHOTEL.NS',
];
